### ISSUE TITLE
The great command format rewrite

### ISSUE THREAD

**Issue by richardjr** [nautoguide/ourthings#3]
So old world we have:

```
<wf-load data-named="MAP1_GEO_UPDATE" data-component="STACK" data-command="PUSH_NAMED_STACK" data-data='{"stackname": "LOCATION", "data": "stack://MAP1_GEOLOCATION/geometry"}'>
```
New world:

```
<wf-load data-command="stack.pushNamedStack" data-json='{}'> or
<wf-event
   <wf-child
```
Possible new formatters suggested:

Close to but you can use any element for the <wf-event>
```
<div data-queue="load" data-command="stack.pushNamedStack" data-json='{}'>
<div data-queue="event" data-command="stack.pushNamedStack" data-json='{}'>
   <wf-child
```

Total rework, more codey less html format, easier to parse
```
@QL::stack.pushNamedStack:{"somejson":"foo"}@
@QE:stack.pushNamedStack:<div blah...>:{"myjson":"stuff}@
  @QC:stack.doSomethingElse:{"morejson":"foo"}@
```

Browser extensions such as <wf-template will remain

**Comment by richardjr** [comment]
Also there could be middle ground between these formats

**Comment by richardjr** [comment]
```
<wf-event:componet.command:
{
 "somenice":"json"
}
>
```

**Comment by el-dunco** [comment]
```
<element is="event" does="#template" english="this element changes a menu class">

<element is="parent" id="this-parent1" does="#template">
<element is="child" parent="this-parent1" does=">
```

Maybe make it a bit more readable?

**Comment by richardjr** [comment]
So:

<element english="This does something" @componet.command({"somenice":"json"});>

**Comment by ng-dan** [comment]
I like the idea of `@component.command({json});` but is that something that will work easily in HTML elements, especially with the potential option of it being multiline?

Personally I'm against the idea of having explanatory text in the element, we've got standard HTML commenting to do that.

**Comment by richardjr** [comment]
You missed the initial office discussion but because the templates will be processed outside the Dom now they can contain invalid html as long as what ends up in the Dom is good. I think the general agreement so far is we don't want to stray too far into codey and away from html though.

Re comments the idea as @dunc points out is that it enforces documenting.

**Comment by ng-dan** [comment]
In that case I'm happy going with that, it's simple and it allows nicer formatting since it's multiline and we won't need to escape '/" like we do currently inside of it.

With comments, how does it enforce documentation unless we're enforcing the presence of it in the element? It seems overkill to document something like (I know we're transitioning away from jQuery but just as a general example)
```
@jquery.tfa({
    target: '#foo',
    function: 'addClass',
    arg: 'bar'
});
```
since it's pretty self explanatory as to what it does.

Overall I think documentation should be handled however the user wants to handle it (if at all), and not be forced in by the library unless it actually serves a functional purpose.

On another note if we go with the `@component.command({json});` structure it might be worth seeing how much effort it would be to create a Webstorm plugin that will do syntax highlighting to help code readability. Though I'm not sure how feasible it would be to expand on the HTML parser to support this

**Comment by richardjr** [comment]
I do agree on the documentation. We can address that in code reviews so I think we are at:

```
<!-- This does something with something -->
<div @componet.command({"somenice":"json"});>
 @componet.othercommand({});
</div>
```

To enable this we will need to either reserve some json variable names IE:

"queueEvent" <- The new name for namedQueue as really its like an event
"queueTimer" <- the old timer

The other option is a second argument that is optional where you can add these options IE:

```
@componet.command({"somenice":"json"},{"queueEvent":"someEvent");
```
This one is probably my preference as its more standard although may make the parser a little harder

**Comment by richardjr** [comment]
In prototyping the parser I have realized the concept of child commands is not present as we can no longer rely on it being a child element of the html. Thus we need:
```
@componet.othercommand({});
 -componet.othercommand({});
 -componet.othercommand({});
```

**Comment by richardjr** [comment]
This is now implemented is basic format. Task left open for adding to user docs
